name: Semgrep
on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 05 5 * * *
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: |
          find . -name "pom.xml" -o -name "build.gradle" -o -name "package.json" -o -name "requirements.txt" -o -name "poetry.lock" -o -name "pyproject.toml" -o -name "Cargo.toml" -o -name "go.mod" -o -name "go.sum" -o -name "Gemfile" -o -name "Gemfile.lock" -exec cp "{}" .  \;
      - run: ls -lah
      - run: git add .
      - run: git commit -m "added manifests & lockfiles"
      - run: semgrep ci
