on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 05 5 * * *
name: Semgrep SAST & SCA
jobs:
  FindManifestAndLockFiles:
      runs-on: ubuntu-latest
      steps:
      - name: find manifest and lock files and upload them as artifacts
        run: |
          find . -name "pom.xml" -o -name "build.gradle" -o -name "package.json" -o -name "requirements.txt" -o -name "poetry.lock" -o -name "pyproject.toml" -o -name "Cargo.toml" -o -name "go.mod" -o -name "go.sum" -o -name "Gemfile" -o -name "Gemfile.lock" -o -name "composer.json" -o -name "composer.lock" -o -name "mix.exs" -o -nam


